version: '3'

services:
  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=mailtrain
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=mailtrain
    ports:
    - "3306:3306"
    volumes:
    - mysql-data:/var/lib/mysql

  redis:
    image: redis:5
    ports:
    - "6379:6379"
    volumes:
    - redis-data:/data

  mongo:
    image: mongo:4-xenial
    ports:
    - "27017:27017"
    volumes:
    - mongo-data:/data/db

  mailtrain:
    build: .
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    volumes:
    - mailtrain-files:/app/server/files

volumes:
  mysql-data:
  redis-data:
  mongo-data:
  mailtrain-files:

